### ISSUE TITLE
run build error~~

### ISSUE THREAD

**Issue by gto999** [wendaosanshou/mi-by-vue#1]
error! i don't know why?

![image](https://cloud.githubusercontent.com/assets/8032538/18119690/684c7004-6f8e-11e6-9aea-ccd94b1ce4e8.png)

**Comment by taomas** [comment]
sorry, the error don't happend when i run the project.

it seem the file `normalize.css`  require path error.

could you modify `import 'normalize.css'` into  `import 'normalize.css/normalize.css'`

**Comment by gto999** [comment]
OK，I Will try it~
