### ISSUE TITLE
关于vue-webpack脚手架

### ISSUE THREAD

**Issue by temool** [wendaosanshou/mi-by-vue#2]
我用的是官方的Vue-webpack脚手架，像你一样配置jQuery，不知道为什么说$未定义，也就是获取不到，想请教一下怎么配置，谢谢

**Comment by taomas** [comment]
我不是太清楚你遇到什么情况，我猜测可能是下面的问题导致的：
- 如果只是eslint报$未定义的话，在`eslintignore`文件里面添加`'globals': {
  "$": true,
  }`
- 如果是$不能全局使用，需要先`npm install jquery --save`然后在`webpack.dev.config.js`和`webpack.prod.config.js`里面先引入jquery,`var jquery = require('jquery')`, 再添加`new webpack.ProvidePlugin({
    $: "jquery"
  })`

可以参考一下`eslintignore`和`webpack.config.js`以及`webpack.prod.js`这几个文件。
