### ISSUE TITLE
关于点击视频css

### ISSUE THREAD

**Issue by xieguo** [wendaosanshou/mi-by-vue#3]
问题一：点击某个视频弹窗播放的transition效果存在问题，导致弹窗的视频无法显示。原代码（PlayVideo.vue）
<template>
    <div class="video-mask" v-show="playConfig.status">
        <div class="video-content"
            v-show="playConfig.status"  //此处
            transition="fadeIn">  //此处
            <div class="video-header clearfix">
                <h3 class="title-txt">{{playConfig.title}}</h3>
                <div class="cancel-link"
                    @click="evtCancel">
                    <i class="cancel-btn fa fa-times"></i>
                </div>
            </div>
            <div class="video">
                <iframe width="880" height="536" :src="playConfig.videoUrl" frameborder="0" allowfullscreen=""></iframe>
            </div>
        </div>
    </div>
</template>

问题二：多个文件的props属性require写错，把required写成required写成require.
props: {
    playConfig: {
      require: true, //正确写法 ？required: true,
      type: Object
    }
  }

**Comment by taomas** [comment]
非常感谢你的反馈。

问题一：视频无法显示我暂时还没有遇到过，不过如果`transition`效果存在问题的话，现在已经修复了，你可以通过[mi-by-vue](http://vue.wendaosanshou.top/mi/)这个地址查看问题是否解决。

问题二：现在代码已经更改，感谢提醒。

建议：这个项目只是一个vue的练手项目。我并没有引入太多的vue.js的一些特性，而且因为没有怎么优化的原因。里面有一些无用代码或者注释代码并没有删除。
如果想系统学习vue.js的话，建议参考[jackblog-vue](https://github.com/jackhutu/jackblog-vue)这个项目。
需要学习vue的组件封装的话，建议参考[radon-ui](https://github.com/wendaosanshou/radon-ui)之类的组件库。
