### ISSUE TITLE
Parsing error: The keyword 'import' is reserved

### ISSUE THREAD

**Issue by boboxiao** [wendaosanshou/mi-by-vue#4]
运行: npm run dev  报错：Parsing error: The keyword 'import' is reserved

**Comment by taomas** [comment]
你在运行`npm run dev`之前有`npm install`吗？

**Comment by boboxiao** [comment]
有。依赖文件已经安装好了！

**Comment by taomas** [comment]
抱歉我好像没有遇到这样的情况。

我猜是不是以下原因导致的。

1.是不是你没有全局安装`vue-cli`。

2.出现这个错误应该就是`babel`相关的`loader`未安装成功。检查一下你的`package.json`文件。
里面的依赖是不是和[package.json](https://github.com/wendaosanshou/mi-by-vue/blob/master/package.json)一致。
如果一致的话再尝试一下`npm install`，或者使用淘宝的镜像试着安装一下依赖。
