### ISSUE TITLE
css是less还是sass.怎么加到wenpack.config里面

### ISSUE THREAD

**Issue by Niofh** [wendaosanshou/mi-by-vue#5]

**Comment by taomas** [comment]
css使用的是sass的写法。

由于node-sass模块在安装过程会比较麻烦，
所以这个项目是使用的post-css里面的precss，写法和sass的写法类似。

webpack的配置路径：
https://github.com/wendaosanshou/mi-by-vue/blob/master/build/webpack.base.conf.js#L84

**Comment by Niofh** [comment]
谢谢,为什么配置比较麻烦?不能在loaders配置吗

**Comment by taomas** [comment]
node-sass国内安装的时候老是安装失败。就没用sass。

**Comment by Niofh** [comment]
为什么我跟着你这样写,也是没有编译成功,因为我自己下载官方的vue-cli模仿你写的

**Comment by taomas** [comment]
可以截图看一下cmd面板的报错信息吗？

**Comment by Niofh** [comment]
他没报错,就是没有反应

**Comment by Niofh** [comment]
https://github.com/598220654/vue-mi.git  这个是我模仿你写的,但是全局引入css字体图标和文件时候,生成dist的路径都错了,你知道什么问题.因为美元说这个项目是你写的,所以专门来模仿你学习vue,能不能帮助我一下,教下我这路径怎么解决!!

**Comment by taomas** [comment]
额，我刚才clone你的项目后发现你并没有安装css依赖！

麻烦尝试一下`npm install font-awesome normalize.css --save-dev`后再重新运行。

你可以比较一下我的package.json和原始的package.json有什么差别。我有引入一些其它的库！

**Comment by Niofh** [comment]
我本地是有的,但是我生成dist的时候所有文件路径都不对...

**Comment by taomas** [comment]
生成dist后路径不对是因为npm-cli的生产文件是需要部署到服务器上的。
而且需要尽量使用绝对路径做资源路径。

如果你需要通过`npm run build`生成dist文件，并且在本地访问的话，可以修改在config/index.js的assetsPublicPath为./,这样能够让html正常引入js、css和image。但是css或js中如果有引入image的话，路径也会错误。

**Comment by taomas** [comment]
本地运行只要`npm run dev`能够跑起来就可以了。只要要部署到服务器上才需要使用`npm run build`来生成dist目录。

**Comment by Niofh** [comment]
哦哦 ,所以我字体图标不出现就是这个问题?要放在服务器上那些字体图标就会出现?? .

**Comment by Niofh** [comment]
我刚刚写了./  但是生成也是/xxx,不是./xxx

**Comment by Niofh** [comment]
我把你的一些东西修改了写,你写了GoodsTop组件,但是没有用上..但我自己也用上了,当做学习,几时出一篇vue-router学习学习啊...(_^__^_)

**Comment by taomas** [comment]
(⊙﹏⊙)b，其实我写的也挺一般的，自己也是在学习vue中！vue-router的话还是看官方文档吧。

这个项目因为只有一个页面，我还没有使用过vue-router，不过我写过的一些其它的项目有用到的。
[https://github.com/wendaosanshou/fecss-blog-vue](https://github.com/wendaosanshou/fecss-blog-vue)，比如这个是最近写的！有用到vue-router。

哈哈，加油吧！
