### ISSUE TITLE
2.0版本下轮播组件出bug

### ISSUE THREAD

**Issue by zengxiaozeng** [wendaosanshou/mi-by-vue#7]
![2 a96sx g1luij1qia g52](https://cloud.githubusercontent.com/assets/8684040/21636179/96762a44-d29c-11e6-8145-055db1fecfa7.png)
![yddb c nkyd3x r_ d k3](https://cloud.githubusercontent.com/assets/8684040/21636183/9c9c38c8-d29c-11e6-8ff5-0e7b073ed8af.png)
这个怎么解决啊    大师    劳烦啊

**Comment by lw8848302** [comment]
滚

**Comment by zengxiaozeng** [comment]
草泥马个沙雕玩意  吃S了吧你
